spring.application.name=diy-shop
spring.datasource.url=jdbc:postgresql://localhost:5432/diyshop
spring.datasource.username=diyshop
spring.datasource.password=diyshop123
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true